import { fact } from '../fact.js';
import type { Phase } from '../types.js';

/**
 * Phase 1 — Manifesto (spec §8.4). Values and team rules → `01-MANIFESTO.md`
 * (human-directed) and `01-AI-LAWS.md` (machine-directed).
 *
 * The candidate rules and machine rules below are the full book-seeded set (M6).
 * The vagueness-check follow-up (§8.4) is not declared here — it is generated by
 * the ANALYSE pass (`src/llm/prompts/analyse.ts`), which flags any rule that cannot
 * be acted upon and asks the user to make it concrete.
 */
export const phase1: Phase = {
  phase: 1,
  name: 'Manifesto',
  seed: [
    {
      id: 'p1.why',
      type: 'editor',
      mapsTo: 'manifesto.why',
      prompt: {
        none: "Why does this need to exist, and who is worse off if it doesn't?",
        some: 'Why does this need to exist, and who is worse off without it?',
        developer: 'Problem statement: why build this, and who is underserved without it?',
      },
      help: 'A few sentences. Write for a person, not a pitch deck.',
      validation: { minWords: 30 },
    },
    {
      id: 'p1.name',
      type: 'text',
      mapsTo: 'projectName',
      prompt: {
        none: 'What do you want to call this? A working name is fine.',
        some: 'Project name or codename?',
        developer: 'Project name / codename?',
      },
    },
    {
      id: 'p1.rules',
      type: 'multiselect',
      mapsTo: 'manifesto.rules',
      prompt: {
        none: 'Which of these should be rules your project lives by? Pick the ones that matter to you.',
        some: 'Which team rules should apply?',
        developer: 'Select the guiding rules for this project.',
      },
      help: 'These become your manifesto. Pick the 8–10 that matter most; you can add your own on the next step.',
      // The book-seeded candidate rules (§8.4). Pick 8–10; the synthesis pass keeps
      // the file to the 8–10 cap and the renderer enforces it.
      options: [
        { value: 'stay-true-to-users', label: 'Stay true to your users' },
        { value: 'ship-before-perfect', label: 'Ship before perfect' },
        { value: 'document-or-it-didnt-happen', label: "Document it or it doesn't exist" },
        {
          value: 'dont-instruct-ai-blindly',
          label: "Don't instruct AI about problems you don't understand",
        },
        { value: 'simple-over-clever', label: 'Choose simple over clever' },
        { value: 'small-steps', label: 'Make it work in small steps' },
        { value: 'delete-more-than-you-add', label: 'Delete more than you add' },
        { value: 'own-your-decisions', label: 'Own every decision the agent makes for you' },
        { value: 'read-before-you-run', label: 'Read the code before you run it' },
        { value: 'security-is-not-later', label: 'Security is not a later problem' },
        { value: 'one-source-of-truth', label: 'Keep one source of truth' },
        { value: 'name-things-honestly', label: 'Name things honestly' },
        { value: 'fail-loudly', label: 'Fail loudly, never silently' },
        { value: 'test-what-would-hurt', label: 'Test what would hurt to break' },
        { value: 'finish-before-starting', label: 'Finish what you start before starting more' },
        { value: 'write-my-own', label: 'Write my own' },
      ],
    },
    {
      id: 'p1.custom-rules',
      type: 'editor',
      mapsTo: 'manifesto.customRules',
      // Only ask when the user asked to write their own on the previous question.
      when: (facts) => {
        const rules = fact(facts, 'manifesto.rules');
        return Array.isArray(rules) && rules.includes('write-my-own');
      },
      prompt: {
        none: 'Write your own rules, one per line.',
        developer: 'Custom rules, one per line.',
      },
      validation: { linesAsList: true },
    },
    {
      id: 'p1.machine-rules',
      type: 'multiselect',
      mapsTo: 'manifesto.machineRules',
      prompt: {
        none: 'Which of these should the AI agent always follow when it writes code for you?',
        some: 'Which machine rules should the agent enforce?',
        developer: 'Machine-directed rules to enforce:',
      },
      // The full machine-rule set (§8.4).
      options: [
        { value: 'docstrings-mandatory', label: 'Docstrings mandatory' },
        { value: 'tests-alongside-features', label: 'Tests alongside features' },
        { value: 'no-unrequested-md', label: 'No unrequested .md files' },
        { value: 'conventional-commits', label: 'Conventional commits' },
        { value: 'typed-everywhere', label: 'Typed everywhere' },
        { value: 'no-new-dependency-without-asking', label: 'No new dependency without asking' },
      ],
    },
  ],
  followUpPolicy: { maxGenerated: 5, onlySeverity: ['blocking', 'important'] },
  synthesis: {
    pass: 'synthesise-manifesto',
    model: 'deep',
    artifacts: ['01-MANIFESTO.md', '01-AI-LAWS.md'],
  },
};
